name: Upload release artifacts

on:
  release:
    types: [published]

env:
  VERSION: ${{ github.event.release.name }}
  REPO_NAME: ${{ github.event.repository.name }}
  OUT_FOLDER: ${{ github.event.repository.name }}
  EXECUTABLE_NAME: ${{ github.event.repository.name }}
  GO_VERSION: '1.23'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Sanity check
      run: |
        echo "Version: ${{ env.VERSION }}"
        echo "Repository name: ${{ env.REPO_NAME }}"
        echo "Out folder: ${{ env.OUT_FOLDER }}"
        echo "Executable name: ${{ env.EXECUTABLE_NAME }}"
        echo "Go version: ${{ env.GO_VERSION }}"
      shell: bash

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Build Linux
      run: go build -o ${{ env.EXECUTABLE_NAME }}
      shell: bash

    - name: Build Windows
      run: GOOS=windows GOARCH=amd64 go build -o ${{ env.EXECUTABLE_NAME }}.exe
      shell: bash

    - name: Create archive
      run: zip ${{ env.OUT_FOLDER}}.zip ${{ env.EXECUTABLE_NAME }} ${{ env.EXECUTABLE_NAME }}.exe
      shell: bash

    - name: Upload artifact
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ env.OUT_FOLDER }}.zip
        asset_name: "${{ env.REPO_NAME }}-${{ env.VERSION }}.zip"
        tag: ${{ github.ref }}