name: Upload release artifacts

on:
  release:
    types: [published]

env:
  VERSION: "${{ github.event.release.name }}"
  REPO_NAME: ${{ github.event.repository.name }}
  OUT_FOLDER: "${{ github.event.repository.name }}.zip"
  GO_VERSION: '1.23'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Sanity check
      run: |
        echo "${{ env.VERSION }}"
        echo "${{ env.REPO_NAME }}"
        echo "${{ env.OUT_FOLDER }}"
        echo "${{ env.GO_VERSION }}"
      shell: bash

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Build Linux
      run: go build -o ${{ env.REPO_NAME }}
      shell: bash

    - name: Set GOOS and GOARCH
      run: GOOS=windows && GOARCH=amd64
      shell: bash

    - name: Build Windows
      run: go build -o ${{ env.REPO_NAME }}.exe
      shell: bash

    - name: Create archive
      run: zip ${{ env.OUT_FOLDER }} ${{ env.REPO_NAME }}
      shell: bash

    - name: Upload artifact
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ env.OUT_FOLDER }}
        asset_name: "${{ env.REPO_NAME }}-${{ env.VERSION }}.zip"
        tag: ${{ github.ref }}